import {
  AppleIcon,
  BellIcon,
  BookIcon,
  BriefcaseIcon,
  CameraIcon,
  ChartNoAxesColumnIcon,
  CodeIcon,
  CoffeeIcon,
  CompassIcon,
  DumbbellIcon,
  FlaskConicalIcon,
  FlowerIcon,
  FolderIcon,
  Gamepad2Icon,
  GlobeIcon,
  GraduationCapIcon,
  HeartIcon,
  HomeIcon,
  LightbulbIcon,
  MailIcon,
  MapPinIcon,
  MicIcon,
  MusicIcon,
  PaletteIcon,
  PawPrintIcon,
  PencilIcon,
  PlaneIcon,
  PopcornIcon,
  PuzzleIcon,
  ScaleIcon,
  ShapesIcon,
  ShoppingBagIcon,
  StarIcon,
  TerminalIcon,
  TrophyIcon,
  UsersIcon,
  WalletIcon,
  WandSparklesIcon,
  WatchIcon,
  WrenchIcon,
} from "lucide-react";
import type { IconPickerColor, IconPickerItem } from "@/components/control-ui/ui/icon-picker";

export const pickerIcons = [
  { value: "folder", label: "Folder", icon: <FolderIcon />, keywords: ["files", "directory"] },
  { value: "wallet", label: "Wallet", icon: <WalletIcon />, keywords: ["money", "finance"] },
  { value: "book", label: "Book", icon: <BookIcon /> },
  { value: "education", label: "Education", icon: <GraduationCapIcon /> },
  { value: "pencil", label: "Pencil", icon: <PencilIcon />, keywords: ["write", "edit"] },
  { value: "sparkles", label: "Magic", icon: <WandSparklesIcon /> },
  { value: "code", label: "Code", icon: <CodeIcon /> },
  { value: "terminal", label: "Terminal", icon: <TerminalIcon /> },
  { value: "music", label: "Music", icon: <MusicIcon /> },
  { value: "popcorn", label: "Popcorn", icon: <PopcornIcon /> },
  { value: "shapes", label: "Shapes", icon: <ShapesIcon /> },
  { value: "palette", label: "Palette", icon: <PaletteIcon />, keywords: ["design", "art"] },
  { value: "coffee", label: "Coffee", icon: <CoffeeIcon /> },
  { value: "puzzle", label: "Puzzle", icon: <PuzzleIcon /> },
  { value: "flower", label: "Flower", icon: <FlowerIcon /> },
  { value: "briefcase", label: "Briefcase", icon: <BriefcaseIcon /> },
  { value: "chart", label: "Chart", icon: <ChartNoAxesColumnIcon /> },
  { value: "watch", label: "Watch", icon: <WatchIcon /> },
  { value: "fitness", label: "Fitness", icon: <DumbbellIcon /> },
  { value: "shopping", label: "Shopping", icon: <ShoppingBagIcon /> },
  { value: "justice", label: "Justice", icon: <ScaleIcon /> },
  { value: "microphone", label: "Microphone", icon: <MicIcon /> },
  { value: "plane", label: "Plane", icon: <PlaneIcon />, keywords: ["travel", "flight"] },
  { value: "globe", label: "Globe", icon: <GlobeIcon /> },
  { value: "tools", label: "Tools", icon: <WrenchIcon /> },
  { value: "pets", label: "Pets", icon: <PawPrintIcon /> },
  { value: "science", label: "Science", icon: <FlaskConicalIcon /> },
  { value: "gamepad", label: "Gamepad", icon: <Gamepad2Icon /> },
  { value: "heart", label: "Heart", icon: <HeartIcon /> },
  { value: "apple", label: "Apple", icon: <AppleIcon /> },
  { value: "star", label: "Star", icon: <StarIcon /> },
  { value: "trophy", label: "Trophy", icon: <TrophyIcon /> },
  { value: "camera", label: "Camera", icon: <CameraIcon /> },
  { value: "bell", label: "Bell", icon: <BellIcon /> },
  { value: "home", label: "Home", icon: <HomeIcon /> },
  { value: "people", label: "People", icon: <UsersIcon /> },
  { value: "mail", label: "Mail", icon: <MailIcon /> },
  { value: "location", label: "Location", icon: <MapPinIcon /> },
  { value: "compass", label: "Compass", icon: <CompassIcon /> },
  { value: "idea", label: "Idea", icon: <LightbulbIcon /> },
] satisfies readonly IconPickerItem[];

export const pickerColors = [
  { value: "default", label: "Default", color: "var(--foreground)" },
  { value: "red", label: "Red", color: "oklch(0.63 0.24 25)" },
  { value: "orange", label: "Orange", color: "oklch(0.69 0.2 45)" },
  { value: "yellow", label: "Yellow", color: "oklch(0.81 0.17 85)" },
  { value: "green", label: "Green", color: "oklch(0.64 0.2 145)" },
  { value: "blue", label: "Blue", color: "oklch(0.59 0.23 255)" },
  { value: "purple", label: "Purple", color: "oklch(0.61 0.25 300)" },
  { value: "pink", label: "Pink", color: "oklch(0.7 0.21 350)" },
] satisfies readonly IconPickerColor[];
