import type { ChatDensity, ChatRole, ChatState } from "../../src/registry/hooks/use-chat-message";
import type { DropzoneVisualState } from "../../src/registry/hooks/use-dropzone";
import type { DynamicNotificationVariant } from "../../src/registry/hooks/use-dynamic-notification";
import type { CodeDiffLineType } from "../../src/registry/lib/diff";
import type { ActivityDetailFormat, ActivityKind, ActivityState } from "../../src/registry/sources/control-ui/activity";
import type { ContextSegmentKind, ContextStatus } from "../../src/registry/sources/control-ui/context-model";
import type { ControlSize } from "../../src/registry/sources/control-ui/control-variants";
import type { DynamicNotificationState } from "../../src/registry/sources/control-ui/dynamic-notification";
import type { InlineAttachmentState } from "../../src/registry/sources/control-ui/inline-attachment";
import type { TaskStatus } from "../../src/registry/sources/control-ui/task-list";
import type { ChatTone } from "../../src/registry/sources/control-ui/transcript-divider";
import type { AlertVariant } from "../../src/registry/sources/control-ui/ui/alert";
import type { BadgeColor, BadgeSize, BadgeVariant } from "../../src/registry/sources/control-ui/ui/badge";
import type { ButtonShape, ButtonTone, ButtonVariant } from "../../src/registry/sources/control-ui/ui/button";
import type { CardVariant } from "../../src/registry/sources/control-ui/ui/card";
import type { CodeChrome, CodeDensity } from "../../src/registry/sources/control-ui/ui/code";
import type { DiffIndicators, DiffStyle } from "../../src/registry/sources/control-ui/ui/code-diff";
import type { DockablePanelContentPadding, DockablePanelPlacement } from "../../src/registry/sources/control-ui/ui/dockable-panel";
import type {
  DrawerContentPadding,
  DrawerContentSurface,
  DrawerContentVariant,
  DrawerSide,
} from "../../src/registry/sources/control-ui/ui/drawer";
import type { DropdownMenuTriggerVariant } from "../../src/registry/sources/control-ui/ui/dropdown-menu";
import type { DropzoneOverlayScope } from "../../src/registry/sources/control-ui/ui/dropzone";
import type { NavigationMenuLinkVariant } from "../../src/registry/sources/control-ui/ui/navigation-menu";
import type { PopoverContentPadding } from "../../src/registry/sources/control-ui/ui/popover";
import type { ResizableHandleVariant, ResizablePanelGroupVariant } from "../../src/registry/sources/control-ui/ui/resizable";
import type { RichTooltipProgressVariant, RichTooltipTone } from "../../src/registry/sources/control-ui/ui/rich-tooltip";
import type { ScrollAreaScrollbarVisibility } from "../../src/registry/sources/control-ui/ui/scroll-area";
import type { SelectTriggerVariant } from "../../src/registry/sources/control-ui/ui/select";
import type { SidebarMenuButtonSize, SidebarMenuButtonVariant } from "../../src/registry/sources/control-ui/ui/sidebar";
import type { SliderVariant } from "../../src/registry/sources/control-ui/ui/slider";
import type { StepperContentMode, StepperOrientation, StepperState } from "../../src/registry/sources/control-ui/ui/stepper";
import type { TableOfContentsVariant } from "../../src/registry/sources/control-ui/ui/table-of-contents";
import type { TabsListVariant } from "../../src/registry/sources/control-ui/ui/tabs";
import type { TimelineState } from "../../src/registry/sources/control-ui/ui/timeline";
import type { ToolbarLinkVariant, ToolbarVariant } from "../../src/registry/sources/control-ui/ui/toolbar";
import type { TreeSelectionIndicator } from "../../src/registry/sources/control-ui/ui/tree";

export type EmittedStateContract = {
  "activity:root:data-activity-kind": ActivityKind;
  "activity:root:data-activity-name": string;
  "activity:root:data-activity-state": ActivityState;
  "activity:announcement:data-status": ActivityState;
  "activity:detail-content:data-format": ActivityDetailFormat;
  "activity:status:data-status": ActivityState;
  "activity:status:data-kind": ActivityKind;
  "context:root:data-status": ContextStatus;
  "context:trigger:data-status": ContextStatus;
  "context:trigger-indicator:data-status": ContextStatus;
  "context:summary:data-status": ContextStatus;
  "context:trigger-track:data-status": ContextStatus;
  "context:trigger-value:data-status": ContextStatus;
  "context:graph:data-status": ContextStatus;
  "context:segment:data-kind": ContextSegmentKind;
  "context:legend-item:data-kind": ContextSegmentKind;
  "context:legend-item:data-tone": "available" | "over-limit";
  "context:legend-indicator:data-kind": ContextSegmentKind;
  "audio-recorder:root:data-disabled": true;
  "audio-recorder:root:data-error": true;
  "audio-recorder:root:data-state": "idle" | "requesting" | "recording" | "recorded" | "submitting" | "error";
  "audio-recorder:trigger:data-recorder-state": "idle" | "requesting" | "recording" | "recorded" | "submitting" | "error";
  "alert:root:data-variant": AlertVariant;
  "autocomplete:input:data-size": ControlSize;
  "badge:root:data-color": BadgeColor;
  "badge:root:data-size": BadgeSize;
  "badge:root:data-variant": BadgeVariant;
  "button:root:data-size": ControlSize;
  "button:root:data-icon-only": true;
  "button:root:data-shape": ButtonShape;
  "button:root:data-tone": ButtonTone;
  "button:root:data-variant": ButtonVariant;
  "card:root:data-variant": CardVariant;
  "button-group:root:data-orientation": "horizontal" | "vertical";
  "button-group:separator:data-orientation": "horizontal" | "vertical";
  "button-group:text:data-size": ControlSize;
  "chat-composer:root:data-density": ChatDensity;
  "chat-composer:root:data-state": "idle" | "submitting" | "disabled";
  "chat-composer:shell:data-state": "idle" | "submitting" | "disabled";
  "chat-composer:mention:data-icon": string;
  "chat-composer:mention:data-id": string;
  "chat-composer:mention:data-mention": string;
  "chat-composer-attachment:root:data-kind": "image" | "pdf" | "spreadsheet" | "document" | "archive" | "audio" | "video" | "file";
  "chat-composer-attachment:root:data-state": "idle" | "uploading" | "uploaded" | "error";
  "chat-composer-attachment:root:data-variant": "preview" | "file";
  "chat-composer-attachment:description:data-state": "idle" | "uploading" | "uploaded" | "error";
  "chat-message:root:data-density": ChatDensity;
  "chat-message:root:data-role": ChatRole;
  "chat-message:root:data-state": ChatState;
  "chat-message:content:data-role": ChatRole;
  "chat-turn:turn:data-from": "user" | "assistant";
  "checkbox-group:root:data-orientation": "horizontal" | "vertical";
  "code:root:data-chrome": CodeChrome;
  "code:root:data-density": CodeDensity;
  "code:line:data-index": number;
  "code-block-editor:root:data-variant": "default" | "command";
  "code-block-editor:root:data-chrome": CodeChrome;
  "code-block-editor:root:data-density": CodeDensity;
  "code-diff:root:data-diff-style": DiffStyle;
  "code-diff:root:data-file-count": number;
  "code-diff:file:data-file-name": string;
  "code-diff:emphasis:data-line-type": CodeDiffLineType;
  "code-diff:line:data-line-type": CodeDiffLineType;
  "code-diff:empty-half:data-side": "left" | "right";
  "code-diff:gutter:data-line-type": CodeDiffLineType;
  "code-diff:line:data-indicators": DiffIndicators;
  "code-diff:line:data-side": "left" | "right";
  "code-diff:marker:data-line-type": CodeDiffLineType;
  "combobox:input:data-size": ControlSize;
  "dockable-panel:root:data-placement": DockablePanelPlacement;
  "dockable-panel:drop-zone:data-side": DockablePanelPlacement;
  "infinite-canvas:root:data-panning": true;
  "infinite-canvas:content:data-scale": number;
  "calendar:day:data-today": true;
  "calendar:day:data-selected-single": true;
  "calendar:day:data-range-start": true;
  "calendar:day:data-range-middle": true;
  "calendar:day:data-range-end": true;
  "dropzone:root:data-disabled": true;
  "dropzone:root:data-empty": true;
  "dropzone:area:data-disabled": true;
  "dropzone:trigger:data-disabled": true;
  "dropzone:overlay:data-active": true;
  "dropzone:file-list:data-empty": true;
  "dropzone:rejection-list:data-empty": true;
  "dropzone:area:data-state": DropzoneVisualState;
  "dropzone:overlay:data-scope": DropzoneOverlayScope;
  "dropzone:overlay:data-state": DropzoneVisualState;
  "dropzone:status:data-state": DropzoneVisualState;
  "dropzone:trigger:data-state": DropzoneVisualState;
  "dynamic-notification:root:data-state": DynamicNotificationState;
  "dynamic-notification:root:data-variant": DynamicNotificationVariant;
  "dynamic-notification:island:data-state": DynamicNotificationState;
  "dynamic-notification:island:data-variant": DynamicNotificationVariant;
  "field:root:data-orientation": "horizontal" | "vertical" | "responsive";
  "inline-attachment:root:data-state": InlineAttachmentState;
  "inline-citation:source:data-activation-direction": "left" | "right";
  "input:root:data-size": ControlSize;
  "input-group:root:data-size": ControlSize;
  "item:root:data-variant": "default" | "outline" | "muted";
  "context-menu:item:data-inset": true;
  "context-menu:label:data-inset": true;
  "context-menu:sub-trigger:data-inset": true;
  "menubar:label:data-inset": true;
  "menubar:sub-trigger:data-inset": true;
  "dropdown-menu:trigger:data-size": ControlSize;
  "dropdown-menu:trigger:data-icon-only": true;
  "dropdown-menu:trigger:data-variant": DropdownMenuTriggerVariant;
  "navigation-menu:link:data-variant": NavigationMenuLinkVariant;
  "dockable-panel:content:data-padding": DockablePanelContentPadding;
  "drawer:content:data-padding": DrawerContentPadding;
  "drawer:content:data-surface-variant": DrawerContentSurface;
  "drawer:content:data-variant": DrawerContentVariant;
  "drawer:content:data-side": DrawerSide;
  "drawer:viewport:data-variant": DrawerContentVariant;
  "drawer:viewport:data-side": DrawerSide;
  "sheet:content:data-side": "left" | "right";
  "popover:content:data-padding": PopoverContentPadding;
  "resizable:handle:data-variant": ResizableHandleVariant;
  "resizable:handle:data-axis": "horizontal" | "vertical";
  "resizable:handle-grip:data-axis": "horizontal" | "vertical";
  "resizable:handle-grip:data-variant": ResizableHandleVariant;
  "rich-tooltip:content:data-tone": RichTooltipTone;
  "rich-tooltip:arrow:data-tone": RichTooltipTone;
  "rich-tooltip:description:data-tone": RichTooltipTone;
  "rich-tooltip:progress:data-tone": RichTooltipTone;
  "rich-tooltip:progress:data-variant": RichTooltipProgressVariant;
  "phone-input:check:data-visible": true;
  "resizable:panel-group:data-variant": ResizablePanelGroupVariant;
  "select:trigger:data-variant": SelectTriggerVariant;
  "toolbar:button:data-icon-only": true;
  "toolbar:link:data-variant": ToolbarLinkVariant;
  "toolbar:root:data-variant": ToolbarVariant;
  "morphing-panel:content:data-state": "open" | "closed";
  "morphing-panel:root:data-state": "open" | "closed";
  "morphing-panel:trigger:data-state": "open" | "closed";
  "native-select:root:data-size": ControlSize;
  "number-field:group:data-size": ControlSize;
  "radio-group:root:data-orientation": "horizontal" | "vertical";
  "select:trigger:data-size": ControlSize;
  "spinner:indicator:data-size": ControlSize;
  "scroll-area:scrollbar:data-visibility": ScrollAreaScrollbarVisibility;
  "sidebar:root:data-collapsible": "offcanvas" | "icon" | "none";
  "sidebar:root:data-side": "left" | "right";
  "sidebar:root:data-state": "expanded" | "collapsed";
  "sidebar:root:data-variant": "sidebar" | "floating" | "inset";
  "sidebar:menu:data-indicator": TreeSelectionIndicator;
  "sidebar:menu-track:data-indicator": TreeSelectionIndicator;
  "sidebar:menu-button:data-active": true;
  "sidebar:menu-button:data-size": SidebarMenuButtonSize;
  "sidebar:menu-button:data-variant": SidebarMenuButtonVariant;
  "slider:root:data-variant": SliderVariant;
  "slider:control:data-labeled": "true";
  "slider:track:data-labeled": "true";
  "slider:track:data-variant": SliderVariant;
  "slider:indicator:data-variant": SliderVariant;
  "slider:thumb:data-variant": SliderVariant;
  "stepper:root:data-content-mode": StepperContentMode;
  "stepper:root:data-orientation": StepperOrientation;
  "stepper:indicator:data-state": StepperState;
  "stepper:item:data-state": StepperState;
  "stepper:item:data-step": number;
  "stepper:list:data-orientation": StepperOrientation;
  "stepper:separator:data-state": StepperState;
  "stepper:trigger:data-state": StepperState;
  "timeline:item:data-state": TimelineState;
  "table-of-contents:root:data-variant": TableOfContentsVariant;
  "table-of-contents:item:data-active": true;
  "table-of-contents:item:data-depth": number;
  "table-of-contents:item:data-level": number;
  "table-of-contents:item:data-variant": TableOfContentsVariant;
  "tabs:list:data-size": ControlSize;
  "tabs:list:data-variant": TabsListVariant;
  "task-list:item:data-status": TaskStatus;
  "task-list:item-indicator:data-status": TaskStatus;
  "thread-rail:item:data-from": ChatRole;
  "transcript-divider:root:data-tone": ChatTone;
  "toggle:root:data-size": ControlSize;
  "toggle:root:data-tone": ButtonTone;
  "toggle:root:data-variant": ButtonVariant;
  "tree:root:data-indicator": TreeSelectionIndicator;
  "tree:track:data-indicator": TreeSelectionIndicator;
  "tree:item:data-disabled": true;
  "tree:item:data-label": string;
  "tree:item:data-selected": true;
  "tree:item:data-value": string;
  "tree:item-trigger:data-selected": true;
};
