import type { ContrastAnatomyArtifact } from "./model";

export function contrastAnatomyModule(artifact: ContrastAnatomyArtifact): string {
  // Typed arguments avoid TypeScript's union-size limit for large probe arrays.
  return [
    "// Generated by scripts/harvest-contrast-anatomy.ts — run `bun run sync:anatomy`.",
    'import type { ContrastAnatomyArtifact, ContrastProbe } from "@/scripts/contrast-anatomy/model";',
    "",
    "export const generatedContrastAnatomy: ContrastAnatomyArtifact = {",
    `version: ${artifact.version},`,
    "probes: Array.of<ContrastProbe>(",
    ...artifact.probes.map((probe) => `${JSON.stringify(probe, null, 2)},`),
    "),",
    `uncovered: ${JSON.stringify(artifact.uncovered, null, 2)},`,
    "};",
    "",
  ].join("\n");
}
