import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { registryItemSchema, registrySchema } from "shadcn/schema";
import { siteConfig } from "@/lib/site-config";
import { formatGeneratedTypeScript } from "./format-generated-typescript";
import { createRegistryItems, publicRegistryDependency } from "./registry-model";

const checkOnly = process.argv.includes("--check");
const root = process.cwd();
const items = createRegistryItems();
const expected = new Map<string, string>();

for (const item of items) {
  const result = registryItemSchema.safeParse(item);
  if (!result.success) throw new Error(`${item.name}: ${result.error.message}`);
  const manifestPath = item.meta?.sourceManifestPath;
  if (!manifestPath) throw new Error(`${item.name} has no source manifest path`);
  expected.set(manifestPath, `${JSON.stringify(item, null, 2)}\n`);
}

const sourceRegistry = {
  $schema: "https://ui.shadcn.com/schema/registry.json",
  name: siteConfig.registry.name,
  homepage: siteConfig.url.origin,
  items: items
    .filter((item) => !item.meta?.internal)
    .map((item) => ({
      ...item,
      registryDependencies: item.registryDependencies.map(publicRegistryDependency),
    })),
};
const registryResult = registrySchema.safeParse(sourceRegistry);
if (!registryResult.success) throw new Error(registryResult.error.message);
expected.set("registry.json", `${JSON.stringify(sourceRegistry, null, 2)}\n`);

const metadata = Object.fromEntries(
  items.map((item) => [
    item.name,
    {
      dependencies: item.dependencies,
      registryDependencies: item.registryDependencies,
      sourceManifestPath: item.meta?.sourceManifestPath,
    },
  ]),
);
expected.set(
  "app/(features)/model/generated-registry.ts",
  formatGeneratedTypeScript(
    "app/(features)/model/generated-registry.ts",
    `// Generated by scripts/gen-registry-manifests.ts.\nexport const registryMetadata = ${JSON.stringify(metadata, null, 2)} as const;\n`,
  ),
);

expected.set(
  "registry/README.md",
  [
    "# Generated — do not edit",
    "",
    "Everything under `registry/` is written by `scripts/gen-registry-manifests.ts` (`bun run sync:manifests`).",
    "Edit the sources in `src/registry/` instead, then run `bun run sync`.",
    "",
  ].join("\n"),
);

const failures: string[] = [];

for (const [filePath, content] of expected) {
  const absolutePath = path.join(root, filePath);
  const current = existsSync(absolutePath) ? readFileSync(absolutePath, "utf8") : undefined;
  if (current === content) continue;
  if (checkOnly) {
    failures.push(`${filePath} is out of date`);
    continue;
  }
  mkdirSync(path.dirname(absolutePath), { recursive: true });
  writeFileSync(absolutePath, content);
}

if (!checkOnly) {
  const expectedPaths = new Set([...expected.keys()].filter((filePath) => filePath.startsWith("registry/")));
  for (const filePath of new Bun.Glob("registry/**/*.json").scanSync({ cwd: root })) {
    if (!expectedPaths.has(filePath)) rmSync(path.join(root, filePath));
  }
}

if (failures.length > 0) {
  console.error(failures.map((failure) => `- ${failure}; run \`bun run sync\``).join("\n"));
  process.exit(1);
}

console.log(checkOnly ? "Registry source manifests are in sync." : `Registry source manifests synced (${items.length} items).`);
