// Derived from same catalog as human docs; `--check` fails on drift.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { practiceSkills, skillConcerns } from "@control-ui/skills";
import { docsPageManifest } from "@/app/(features)/catalog/pages";
import type { SearchItem } from "@/app/(features)/model/types";
import { listRegistry } from "@/app/(features)/registry-api/registry-index";
import { contrastAgentRules } from "@/app/(features)/theme-accessibility/agent-rules";
import { env } from "@/env";
import { absoluteSiteUrl, siteConfig } from "@/lib/site-config";
import { publicPayloads } from "./public-payloads";

const MARKER_NAMESPACE = siteConfig.registry.name.toUpperCase();
const START = `<!-- ${MARKER_NAMESPACE}:START -->`;
const END = `<!-- ${MARKER_NAMESPACE}:END -->`;

const KIND_SECTIONS: { kind: SearchItem["kind"]; heading: string }[] = [
  { kind: "Agent", heading: "Agents (installable components)" },
  { kind: "Block", heading: "Blocks (pre-composed recipes)" },
  { kind: "Primitive", heading: "Primitives" },
  { kind: "Extension", heading: "Extensions" },
  { kind: "Skin", heading: "Skins" },
  { kind: "Hook", heading: "Hooks" },
  { kind: "Util", heading: "Utils" },
  { kind: "Guide", heading: "Guides" },
];

const LLMS_SECTIONS: { kind: SearchItem["kind"]; heading: string }[] = [
  { kind: "Guide", heading: "Documentation" },
  { kind: "Agent", heading: "AI components" },
  { kind: "Block", heading: "Blocks" },
  { kind: "Primitive", heading: "Primitives" },
  { kind: "Extension", heading: "Extensions" },
  { kind: "Skin", heading: "Skins" },
  { kind: "Hook", heading: "Hooks" },
  { kind: "Util", heading: "Utilities" },
  { kind: "Skill", heading: "Practice guides" },
];

function itemLine(item: { id: string; name: string; summary: string; install?: string; status?: SearchItem["status"] }) {
  const install = item.install ? ` — \`${item.install}\`` : "";
  const status = item.status ? ` **[${item.status}]**` : "";
  return `- \`${item.id}\` (${item.name})${status} — ${item.summary}${install}`;
}

function skillsBlock() {
  return skillConcerns
    .map((concern) => {
      const skills = practiceSkills.filter((skill) => skill.concern === concern.id);
      if (skills.length === 0) return undefined;
      const lines = skills.map((skill) => {
        const doList = skill.checks.length > 0 ? `\n  - do: ${skill.checks.join(" ")}` : "";
        const avoidList = skill.avoid.length > 0 ? `\n  - avoid: ${skill.avoid.join(" ")}` : "";
        return `- **${skill.title}** — ${skill.goal}${doList}${avoidList}`;
      });
      return `### ${concern.title}\n${lines.join("\n")}`;
    })
    .filter(Boolean)
    .join("\n\n");
}

const contrastBlock = (base: string) =>
  contrastAgentRules(base)
    .map((rule) => `- ${rule}`)
    .join("\n");

function buildCheatSheet() {
  const { items } = listRegistry().data;
  const base = env.NEXT_PUBLIC_REGISTRY_URL;

  const sections = KIND_SECTIONS.map(({ kind, heading }) => {
    const group = items.filter((item) => item.kind === kind);
    if (group.length === 0) return undefined;
    return `### ${heading}\n${group.map(itemLine).join("\n")}`;
  }).filter(Boolean);

  return [
    `# ${siteConfig.name} registry — agent cheat-sheet`,
    "",
    "> Generated by `bun run docs:agents` from the registry catalog. Do not edit inside the markers.",
    "",
    "## How to use this registry",
    "",
    `- Discover: \`GET ${base}/api/registry\` (or the static \`${base}/r/agent-index.json\`) → the agent-friendly index.`,
    `- shadcn catalog: \`${base}/r/registry.json\` → the official registry schema used by shadcn tooling.`,
    `- Read one item: \`GET ${base}/api/registry/<id>\` → source files, install command, and deps.`,
    `- Search: \`GET ${base}/api/registry/search?q=<query>\`.`,
    `- Skin anatomy: \`${base}/r/contract/index.json\` lists every paint family; read \`${base}/r/contract/<family>.json\` for the family you restyle, its \`.contrast.json\` sibling for what paints behind it, and \`GET ${base}/api/registry/<id>\` for one item's slice. Do not guess selectors.`,
    "- Component knobs: every component paints through registered `--cui-<family>-*` CSS custom properties (e.g. `--cui-button-radius`). A family slice carries its knobs with syntax and recipe defaults; restyle per instance via the typed `style` prop or from a skin, never by overriding Tailwind classes.",
    "- Install: run the item's `install` command (`npx shadcn@latest add <url>`). Installed files are yours to own and edit.",
    "- Skinning: a skin is additive CSS + a `skin.config`; install a skin pack to restyle every component at once.",
    `- Setting up a repository from scratch: \`${base}/r/${publicPayloads.setupPrompt}\` is the full procedure, including the wiring steps that fail silently when skipped.`,
    `- Working where Control UI is already installed: \`${base}/r/${publicPayloads.controlUiSkill}\` is the installable skill carrying the token contract and the working rules (mirrored at \`skills/control-ui/SKILL.md\`).`,
    "",
    "## Contrast (check this before shipping a skin)",
    "",
    contrastBlock(base),
    "",
    "## Catalog",
    "",
    sections.join("\n\n"),
    "",
    "## Practice rules (how to build well)",
    "",
    skillsBlock(),
    "",
  ].join("\n");
}

function llmsItemLine(item: SearchItem) {
  const status = item.status ? ` Status: ${item.status}.` : "";
  return `- [${item.name}](${absoluteSiteUrl(item.href)}): ${item.summary}${status}`;
}

function buildLlmsIndex() {
  const sections = LLMS_SECTIONS.map(({ kind, heading }) => {
    const pages = docsPageManifest.filter((page) => page.kind === kind);
    if (pages.length === 0) return undefined;
    return `## ${heading}\n\n${pages.map(llmsItemLine).join("\n")}`;
  }).filter(Boolean);

  return [
    `# ${siteConfig.name}`,
    "",
    `> ${siteConfig.description}`,
    "",
    `${siteConfig.name} installs editable React source through the shadcn CLI. The catalog below is generated from the same page manifest used by the website, sitemap, search, and registry API.`,
    "",
    sections.join("\n\n"),
    "",
    "## Machine-readable indexes",
    "",
    `- [Registry API](${absoluteSiteUrl("/api/registry")}): JSON index of every public catalog item.`,
    `- [Agent index](${absoluteSiteUrl("/r/agent-index.json")}): Static agent-friendly registry metadata.`,
    `- [shadcn registry](${absoluteSiteUrl("/r/registry.json")}): Registry schema consumed by shadcn tooling.`,
    `- [Skin anatomy contract](${absoluteSiteUrl("/r/contract/index.json")}): Index of every paint family. Each family slices its own scopes, parts, states, knobs (the \`--cui-*\` CSS custom properties every component paints through), and adornments, with a \`.contrast.json\` sibling carrying the rendered ancestor chain that paints behind each one.`,
    `- [Theme token contract](${absoluteSiteUrl("/r/theme-contract.json")}): Generated skin token reference.`,
    `- [Setup prompt](${absoluteSiteUrl(`/r/${publicPayloads.setupPrompt}`)}): Paste-ready instructions for a coding agent: read a repository, install ${siteConfig.name} into it, wire the CSS, then design and contrast-check its skin.`,
    "",
    "## Optional",
    "",
    `- [Extended agent reference](${absoluteSiteUrl("/llms-full.txt")}): Detailed catalog, install commands, and ${siteConfig.name} practice rules.`,
    "",
  ].join("\n");
}

function buildLlmsFull(generatedCheatSheet: string) {
  return generatedCheatSheet
    .replace(`# ${siteConfig.name} registry — agent cheat-sheet`, `# ${siteConfig.name} — extended agent reference`)
    .replace(
      "> Generated by `bun run docs:agents` from the registry catalog. Do not edit inside the markers.",
      `> ${siteConfig.description}`,
    )
    .replaceAll(env.NEXT_PUBLIC_REGISTRY_URL, siteConfig.url.origin);
}

function injectMarkers(existing: string, block: string) {
  const wrapped = `${START}\n${block}\n${END}`;
  const startIndex = existing.indexOf(START);
  const endIndex = existing.indexOf(END);
  if (startIndex !== -1 && endIndex !== -1 && endIndex > startIndex) {
    return `${existing.slice(0, startIndex)}${wrapped}${existing.slice(endIndex + END.length)}`;
  }
  const separator = existing.endsWith("\n") ? "\n" : "\n\n";
  return `${existing.trimEnd()}\n${separator}${wrapped}\n`;
}

const checkOnly = process.argv.includes("--check");
const cheatSheet = buildCheatSheet();
const llmsIndex = buildLlmsIndex();
const llmsFull = buildLlmsFull(cheatSheet);
const repoRoot = path.resolve(process.cwd(), "../..");

const targets: { path: string; expected: string; missingOk?: boolean }[] = [];

for (const file of ["AGENTS.md", "CLAUDE.md"]) {
  const absolute = path.join(repoRoot, file);
  if (!existsSync(absolute)) {
    // CLAUDE.md is only injected when repo already has one
    continue;
  }
  targets.push({ path: absolute, expected: injectMarkers(readFileSync(absolute, "utf8"), cheatSheet) });
}

targets.push(
  { path: path.join(process.cwd(), "public/llms.txt"), expected: `${llmsIndex.trimEnd()}\n` },
  { path: path.join(process.cwd(), "public/llms-full.txt"), expected: `${llmsFull.trimEnd()}\n` },
);

const drift: string[] = [];
for (const target of targets) {
  const current = existsSync(target.path) ? readFileSync(target.path, "utf8") : undefined;
  if (current === target.expected) continue;

  if (checkOnly) {
    drift.push(`- ${path.relative(repoRoot, target.path)} is out of date; run \`bun run docs:agents\``);
    continue;
  }
  writeFileSync(target.path, target.expected);
}

if (drift.length > 0) {
  console.error(drift.join("\n"));
  process.exit(1);
}

console.log(checkOnly ? "Agent docs are in sync." : `Agent docs synced (${targets.length} file(s)).`);
