import type { PracticeSkillDefinition } from "../types";

export const controlUiSkills = [
  {
    id: "skin-authoring",
    title: "Skin authoring",
    concern: "control-ui",
    summary:
      "Author a skin as three files with strict roles — theme.css owns the complete token contract, skin.config restyles slots and declares DS choices, skin.css says only what classes cannot.",
    goal: "Make every pack self-contained and composable with the library recipes: tokens stay editor-hydratable, slot overrides merge by tailwind-merge argument order, and no skin inherits another skin's visual values.",
    source: {
      label: "Skin contract & doctrine (file-level comment)",
      path: "src/registry/skin.ts",
    },
    checks: [
      "Start every visual change at the lowest rung of the customization ladder (/architecture#customization-ladder): a contract token in theme.css first; then a DS-level `ControlUiSkin` field (`sidebarLayout`, `sidebarWidth`, `indicators`, `motion`, `colorScheme`, `effects`) when the whole app should flip at once; then a `skin.config` slot; then skin.css; a shared `@utility` or an extension only after that.",
      "Restyle a recipe-painted property (background, border, radius, shadow — anything the component's cva/classes already set) through `skinSlot`: the config string evicts the library utility by tailwind-merge ARGUMENT ORDER, state variants included, with no cascade fight and the caller's className still winning last.",
      "theme.css resolves every contract token in BOTH light and dark, either through a shared declaration or explicit mode declarations; skin-local formulas are allowed, but missing values are not. Packs never open their own `@theme` block — core owns bindings and invariant mechanics, never visual token defaults (test-enforced).",
      'Scope every skin under `[data-skin="<id>"]` and stamp exactly one valid id on the application root. The id is the design system\'s name, lets several packs compile in one build, and is re-asserted on portalled surfaces. Missing or unknown ids have no implicit Refined/core fallback.',
      'Variables the pack invents (`--<pack>-*`) are declared in skin.css beside the rules that read them, scoped `[data-skin="<id>"]` — never added to theme.css and never leaked unscoped.',
      'skin.css keeps to what classes cannot express: pseudo-elements, keyframes, native scrollbars, root/body inheritance, relational and state selectors, and a uniform multi-slot FAMILY (one DS concept — a popup material, a control treatment — applied to many slots by one documented rule) ONLY on properties the recipes do not already paint as utilities: where they do, the family rule silently loses and the concept belongs in a shared const spread across the config\'s slot entries. Everything stays scoped to the skin id, inside `@layer components`, with literal `[data-control-ui="<scope>"][data-slot="<part>"]` anatomy selectors.',
      "When the element you need to restyle has no part in `SkinSlotContexts`, add the part and resolve it with `skinSlot(scope, part, context)` — growing the generated contract is part of adding the part, and every future skin benefits.",
      'A pack\'s behavioral fx activates through nested `adornments` on the component\'s named anchor (e.g. `adornments: { "chat-composer": { "send-layer": (ctx) => <SendAurora sendCount={ctx.sendCount} /> } }`) — the referenced extension lives in a separate "use client" file the pack ships, the config stays RSC-pure, and the manifest lists the extension files as additional targets (liquid-metal/send-aurora precedent).',
      'Row-list parts (`sidebar.menu-button`, `tree.item-trigger`) may paint hover/active backgrounds freely: under `indicator="slide"` the library resets them after your classes so the pill stays the sole chrome. Keep row backgrounds on the bare or `dark:` modifier chains the reset restates (test-enforced), or take a function-form slot and branch on `ctx.indicator`.',
      "Run the pack test suite from apps/docs (`bun test`): complete light/dark contract coverage, no core defaults, no-@theme, fixture parity, and popover surface consistency are enforced requirements.",
    ],
    avoid: [
      "`!important` (or the Tailwind `!` suffix) in skin.css to restyle a SINGLE slot's recipe-painted property — that is the exact cascade fight `skinSlot` eviction exists to avoid; a rule in `@layer components` without `!important` on such a property silently loses to the utility layer and ships dead.",
      "Painting the same slot in both skin.config and skin.css: one of the two silently wins and the other drifts unnoticed until it resurfaces as a half-applied look.",
      "The `!` important suffix inside skin.config classes: it does not just beat sibling utilities — it beats the caller's className that cn() puts LAST, breaking caller-wins. When tailwind-merge fails to evict a recipe shadow it is the ambiguous `shadow-[var(--x)]` form (classified as a shadow COLOR); write `shadow-(--x)` — classified as box-shadow, evicts by argument order.",
      "Bare host-element selectors (`button`, `input`, `code`) or un-layered rules — they leak past the component anatomy and outlive the skin's scope.",
      "`animation: none` for calm variants — the motion kill-switch collapses `--duration-*` to 0ms so `animationend` cleanup still fires (the ripple depends on it); disable durations through tokens, never the animation itself.",
      "Hardcoding geometry the token contract already parameterizes (radius, control heights): prefer the token, or a floor like `rounded-[max(3px,var(--radius-control))]` so editor knobs stay live on chrome skins.",
    ],
  },
  {
    id: "extension-authoring",
    title: "Extension authoring",
    concern: "control-ui",
    summary:
      "Author an extension as an optional installable layered on the library — root-mounted for cross-cutting anatomy-attached behavior, anchored for component-scoped fx activated from skin.config.",
    goal: "Every fx lands on exactly one mechanism, costs nothing when absent, and keeps its a11y/perf guarantees in the component-owned wrapper instead of hand-rolled placement.",
    source: {
      label: "Extension taxonomy & anchor contract",
      path: "src/registry/skin.ts",
    },
    checks: [
      "Sort the fx first (/architecture#extension-contract): persistent state → plain CSS on the emitted data-state/data-slot anatomy, no mechanism; transient skin-owned event → an anchored extension; per-instance decoration → call-site composition; cross-cutting uniformity → a root extension; behavior needing internals that many skins want → an integrated behavior (lazy + `ControlUiSkin` field); everything else → rung 8.",
      "An anchor is ONE position contract owned by the component: it ships the positioned wrapper (aria-hidden, pointer-events-none, `contain: paint`, clipping) rendered only when `skinAdornment(...)` resolves, and the extension only supplies visuals — never a portal, never its own positioning.",
      "Anchor ctx carries plain render-time values (a render prop, not React Context); state that only feeds an anchor is guarded by `hasSkinAdornment(...)` so unfilled apps pay no extra update (the `trackSends` precedent in use-chat-composer).",
      'One-shot replay is structural: key the layer on a ctx counter and play a mount-time keyframe/@starting-style that parks invisible; every duration rides `--duration-*` so `data-motion="reduced"` collapses it for free.',
      "Theme the extension through its own component-local tokens with baseline defaults in its CSS (`--aurora-*`), re-valuable by a pack and overridable inline via a typed prop — never hardcoded colors.",
      'Root extensions attach by semantic family (`[data-control-ui][data-control="true"]`), mount once above their targets (a route segment counts), delegate events, and park when their skin is inactive (liquid-metal\'s gated observer).',
      "Ship every extension as its own registry item (`registry:style` or component+CSS) so the install boundary IS the cost boundary; a pack that activates it lists the same files in its manifest so both install paths stay byte-identical (validate-registry allowlist).",
      'Components without an anchor carry the breadcrumb comment with the canonical slug (`{/* fx anchor candidate: "<component>:<layer>" */}`) — documentation and promotion path, never an activation channel.',
    ],
    avoid: [
      "CustomEvent buses or context providers to notify a component-scoped extension — the anchored render prop already delivers typed values with no indirection.",
      "Portals for anchored layers: the component's own stacking context is the contract; a portal escapes the wrapper's a11y/hit-test/containment guarantees.",
      "Baking an fx into a component because one design wants it — that ships bytes to every install; anchor it and let skin.config decide.",
      "Presenting the breadcrumb comment as wiring users must fill, or activating extensions anywhere but skin.config (anchored) / an explicit layout mount (root).",
    ],
  },
  {
    id: "registry-first-dx",
    title: "Registry-first DX",
    concern: "control-ui",
    summary: "Keep the registry manifest and installed source as the contract users can inspect.",
    goal: "Keep the shadcn registry as the install source of truth while avoiding copied demo-only code.",
    checks: [
      "Every installable file is referenced by a registry manifest.",
      "Docs snippets are read from real source files.",
      "Generated fixtures are checked by validation scripts.",
    ],
    avoid: ["Maintaining raw code strings in docs.", "Publishing a package API before the registry contract is stable."],
  },
  {
    id: "skin-completeness",
    title: "Skin completeness",
    concern: "control-ui",
    summary: "Treat a skin as a complete source recipe, not a partial class override layer.",
    goal: "Make every skin a complete visual layer for the public Control UI component set.",
    checks: [
      "Each skin implements the same documented component files.",
      "Each skin's theme.css explicitly resolves the complete token contract in light and dark without inheriting Refined or core values.",
      "Skins can replace UI dependencies when the visual behavior needs more than classes.",
      "Adapters never import skin internals.",
    ],
    avoid: ["Partial skins that only work on one block.", "Variant matrices for theme-level differences."],
  },
  {
    id: "control-ui-composition",
    title: "Control UI composition",
    concern: "control-ui",
    summary: "Keep blocks readable by composing public agent components, hooks, and slots explicitly.",
    goal: "Prefer explicit React composition so advanced blocks remain readable after installation.",
    checks: [
      "Blocks compose documented top-level components.",
      "Actions are children, not data arrays, when the user may customize layout.",
      "Reusable behavior lives in hooks or context, not in theme code.",
    ],
    avoid: ["Component factories in installed skin files.", "Duplicated behavior between component source and skin packs."],
  },
  {
    id: "runtime-agnostic-ui",
    title: "Runtime-agnostic UI",
    concern: "control-ui",
    summary: "Keep core visual surfaces independent from model runners, stores, and transport lifecycles.",
    goal: "Keep Control UI core components independent from model runners, message stores, and transport lifecycles.",
    checks: [
      "Core components render from plain props and children without requiring a runtime provider.",
      "Context is only used for local UI anatomy or behavior, such as role, density, open state, copy value, or submit state.",
      "Provider-specific code lives in usage examples or host-app mapping functions, not installed core files.",
      "Blocks compose UI components and callbacks without owning model calls, streaming transport, persistence, branching, or tool execution.",
    ],
    avoid: [
      "AssistantRuntimeProvider-style APIs that make UI components depend on one runtime shape.",
      "Importing Mastra, AI SDK, LangChain, or custom runner packages from skins or core components.",
      "Hiding message/thread/run lifecycle inside visual components.",
      "Installing runner adapters as the default path for rendering the UI.",
    ],
  },
  {
    id: "compound-components-dx",
    title: "Compound components DX",
    concern: "control-ui",
    summary: "Expose named anatomy parts when users need to customize layout or actions.",
    goal: "Prefer anatomy-based compound components over large prop bags for customizable Control UI surfaces.",
    checks: [
      "Expose meaningful parts such as Root, Header, Content, Actions, Media, Title, and Submit when users may customize layout.",
      "Keep data or state props only where they drive behavior, such as from, state, value, onSubmit, or code.",
      "Type each part with ComponentProps<> for its rendered element or base UI component.",
      "Forward remaining native props with ...props and let users customize each part with className.",
    ],
    avoid: [
      "Adding new visual props when a child component slot would be clearer.",
      "Centralized classNames slot objects for components that can expose real parts.",
      "Data arrays for actions or toolbar items when users should compose children directly.",
    ],
  },
  {
    id: "context-vs-props",
    title: "Context vs props",
    concern: "control-ui",
    summary: "Reach for a compound-component context only when props cannot reach the part, and store intent in it, not styling.",
    goal: "Keep compound-component context to the cases props cannot cover, and put semantic intent in the value rather than precomputed classes.",
    checks: [
      "Add a context only when both hold: the Root owns something parts need (state, or a mode that also styles the Root), and consumers place those parts in JSX you do not control, so a prop cannot reach them.",
      "Store the smallest semantic value — modes, flags, callbacks — and let each part derive its own classes; do not freeze precomputed className strings in the value.",
      "Let a per-part prop override the context default (`maxHeight ?? context.maxHeight`), so context is the cascade and props are the escape hatch.",
    ],
    avoid: [
      "Creating a context for parts you fully control or that share nothing with the Root — pass props instead.",
      "Freezing precomputed Tailwind strings in the context value, which couples every part to the Root and blocks skins from varying by attribute.",
    ],
  },
] as const satisfies readonly PracticeSkillDefinition[];
