import { preview, sourceFile } from "./shared";

export const hookEntries = [
  {
    id: "use-chat-message",
    kind: "Hook",
    name: "useChatMessage",
    summary: "Typed role, density, and tone state for ChatMessage.",
    target: "components/control-ui/hooks/use-chat-message.ts",
    install: "the ChatMessage component",
    source: sourceFile("Behavior hook", "src/registry/hooks/use-chat-message.ts", "hook"),
    references: [{ label: "ChatMessage", href: "/ai/chat-message" }],
  },
  {
    id: "use-chat-composer",
    kind: "Hook",
    name: "useChatComposer",
    summary: "Controlled composer text and submit state.",
    target: "components/control-ui/hooks/use-chat-composer.ts",
    install: "the ChatComposer component",
    source: sourceFile("Behavior hook", "src/registry/hooks/use-chat-composer.ts", "hook"),
    references: [{ label: "ChatComposer", href: "/ai/chat-composer" }],
  },
  {
    id: "use-user-ask",
    kind: "Hook",
    name: "useUserAsk",
    summary: "Question/option registration, selection, freeform text, and keyboard flow for UserAsk.",
    target: "components/control-ui/hooks/use-user-ask.ts",
    install: "the UserAsk component",
    source: sourceFile("Behavior hook", "src/registry/hooks/use-user-ask.ts", "hook"),
    references: [{ label: "UserAsk", href: "/ai/user-ask" }],
  },
  {
    id: "use-audio-recorder",
    kind: "Hook",
    name: "useAudioRecorder",
    summary: "Browser microphone recording state, waveform levels, and Blob completion.",
    target: "components/control-ui/hooks/use-audio-recorder.ts",
    install: "the AudioRecorder component",
    source: sourceFile("Behavior hook", "src/registry/hooks/use-audio-recorder.ts", "hook"),
    references: [{ label: "AudioRecorder", href: "/ai/audio-recorder" }],
  },
  {
    id: "use-environment-variables",
    kind: "Hook",
    name: "useEnvironmentVariables",
    summary: "Editable environment variable rows with .env parsing, upload, duplicate detection, and submit helpers.",
    target: "components/control-ui/hooks/use-environment-variables.ts",
    install: "the EnvironmentVariables component",
    source: sourceFile("Behavior hook", "src/registry/hooks/use-environment-variables.ts", "hook"),
    references: [{ label: "EnvironmentVariables", href: "/ai/environment-variables" }],
  },
  {
    id: "use-copy-to-clipboard",
    kind: "Hook",
    name: "useCopyToClipboard",
    summary: "Copy-to-clipboard behavior with success state and fallback support.",
    target: "components/control-ui/hooks/use-copy-to-clipboard.ts",
    install: "copy-enabled components",
    source: sourceFile("Behavior hook", "src/registry/hooks/use-copy-to-clipboard.ts", "hook"),
    references: [
      { label: "ActionBar", href: "/ai/action-bar" },
      { label: "MarkdownBlock", href: "/ai/markdown-block" },
      { label: "CodeBlockEditor", href: "/ai/code-block-editor" },
    ],
  },
] as const;

export const utilEntries = [
  {
    id: "cn",
    kind: "Util",
    name: "cn",
    summary: "Tailwind class-name merge helper.",
    target: "components/control-ui/lib/cn.ts",
    source: sourceFile("Class-name helper", "src/registry/lib/cn.ts", "util"),
  },
  {
    id: "skin",
    kind: "Util",
    name: "skin",
    summary: "Skin slot and adornment resolvers for the Control UI library.",
    target: "components/control-ui/skin.ts",
    source: sourceFile("Skin resolver", "src/registry/skin.ts", "util"),
  },
  {
    id: "contracts",
    kind: "Util",
    name: "contracts",
    summary: "Shared prop and slot contracts for swappable skins.",
    target: "components/control-ui/contracts.ts",
    source: sourceFile("Type contracts", "src/registry/contracts.ts", "util"),
  },
  {
    id: "serialize",
    kind: "Util",
    name: "serialize",
    summary: "Bridge a rich editor doc to plain text (and structured mentions) and back — independent of any one component.",
    target: "components/control-ui/chat-composer-editor/serialize.ts",
    install: "the ChatComposer rich editor",
    source: sourceFile("Serializer", "src/registry/sources/control-ui/chat-composer-editor/serialize.ts", "util"),
    // Live preview: rich editor doc serializes to { text, mentions } as you type.
    preview: preview(() => import("@/src/registry/examples/control-ui/serialize").then((mod) => ({ default: mod.SerializeExample }))),
    references: [
      { label: "ChatComposer", href: "/ai/chat-composer" },
      { label: "Chat block", href: "/use-cases/chat" },
    ],
  },
] as const;
