import type { KnobRule } from "@/components/theme-drawer/types";
import { KNOB_REGISTRY } from "./knob-registry";

export type KnobEntry = { name: string; syntax: string; defaultValue: string; selector: string };
export type KnobFamilySummary = { id: string; knobCount: number; sample: readonly string[] };
export type KnobRejection = { name: string; reason: string };

const SAMPLE_SIZE = 6;
const MAX_VALUE_LENGTH = 128;

// Generated by scripts/gen-knob-registry.ts rather than parsed here: the recipe stylesheets are build
// inputs, and a serverless function is shipped without them.
const knobsByFamilyId = new Map<string, readonly KnobEntry[]>(KNOB_REGISTRY.map((family) => [family.id, family.knobs]));

const knobsByName = new Map<string, KnobEntry>(KNOB_REGISTRY.flatMap((family) => family.knobs.map((knob) => [knob.name, knob] as const)));

const familySummaries: readonly KnobFamilySummary[] = KNOB_REGISTRY.map((family) => ({
  id: family.id,
  knobCount: family.knobs.length,
  sample: family.knobs.slice(0, SAMPLE_SIZE).map((knob) => knob.name),
}));

export function knobFamilySummaries(): readonly KnobFamilySummary[] {
  return familySummaries;
}

export function knobsForFamily(familyId: string): readonly KnobEntry[] {
  return knobsByFamilyId.get(familyId) ?? [];
}

const NUMBER = String.raw`[+-]?(?:\d+\.?\d*|\.\d+)`;
const ZERO = String.raw`[+-]?(?:0+(?:\.0*)?|\.0+)`;
const LENGTH_UNITS = [
  "cqmin",
  "cqmax",
  "vmin",
  "vmax",
  "rlh",
  "svw",
  "svh",
  "lvw",
  "lvh",
  "dvw",
  "dvh",
  "cqw",
  "cqh",
  "cqi",
  "cqb",
  "cap",
  "rem",
  "px",
  "em",
  "ch",
  "ex",
  "ic",
  "lh",
  "vw",
  "vh",
  "vi",
  "vb",
  "pt",
  "pc",
  "in",
  "cm",
  "mm",
  "q",
].join("|");

const numberPattern = new RegExp(`^${NUMBER}$`);
const integerPattern = /^[+-]?\d+$/;
const lengthPattern = new RegExp(`^(?:${NUMBER}(?:${LENGTH_UNITS})|${ZERO})$`, "i");
const percentagePattern = new RegExp(`^${NUMBER}%$`);
const timePattern = new RegExp(`^${NUMBER}(?:ms|s)$`, "i");
const anglePattern = new RegExp(`^${NUMBER}(?:grad|deg|rad|turn)$`, "i");
const hexColorPattern = /^#(?:[0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$/i;
const colorFunctionPattern = /^(?:oklch|rgba?|hsla?|lab|lch|color-mix|color)\(/i;
const computedValuePattern = /^(?:var|calc|min|max|clamp)\(/i;
const keywordPattern = /^[a-z][a-z0-9-]*$/i;

const NAMED_COLORS: Record<string, true> = Object.fromEntries(
  `transparent currentcolor aliceblue antiquewhite aqua aquamarine azure beige bisque black blanchedalmond blue
   blueviolet brown burlywood cadetblue chartreuse chocolate coral cornflowerblue cornsilk crimson cyan darkblue
   darkcyan darkgoldenrod darkgray darkgreen darkgrey darkkhaki darkmagenta darkolivegreen darkorange darkorchid
   darkred darksalmon darkseagreen darkslateblue darkslategray darkslategrey darkturquoise darkviolet deeppink
   deepskyblue dimgray dimgrey dodgerblue firebrick floralwhite forestgreen fuchsia gainsboro ghostwhite gold
   goldenrod gray green greenyellow grey honeydew hotpink indianred indigo ivory khaki lavender lavenderblush
   lawngreen lemonchiffon lightblue lightcoral lightcyan lightgoldenrodyellow lightgray lightgreen lightgrey
   lightpink lightsalmon lightseagreen lightskyblue lightslategray lightslategrey lightsteelblue lightyellow lime
   limegreen linen magenta maroon mediumaquamarine mediumblue mediumorchid mediumpurple mediumseagreen
   mediumslateblue mediumspringgreen mediumturquoise mediumvioletred midnightblue mintcream mistyrose moccasin
   navajowhite navy oldlace olive olivedrab orange orangered orchid palegoldenrod palegreen paleturquoise
   palevioletred papayawhip peachpuff peru pink plum powderblue purple rebeccapurple red rosybrown royalblue
   saddlebrown salmon sandybrown seagreen seashell sienna silver skyblue slateblue slategray slategrey snow
   springgreen steelblue tan teal thistle tomato turquoise violet wheat white whitesmoke yellow yellowgreen`
    .trim()
    .split(/\s+/)
    .map((color) => [color, true]),
);

const baseTypeMatchers: Record<string, (term: string) => boolean> = {
  length: (term) => lengthPattern.test(term),
  percentage: (term) => percentagePattern.test(term),
  "length-percentage": (term) => lengthPattern.test(term) || percentagePattern.test(term),
  number: (term) => numberPattern.test(term),
  integer: (term) => integerPattern.test(term),
  time: (term) => timePattern.test(term),
  angle: (term) => anglePattern.test(term),
  color: (term) => NAMED_COLORS[term.toLowerCase()] === true || hexColorPattern.test(term) || colorFunctionPattern.test(term),
};

function splitTopLevelTerms(value: string): string[] {
  const terms: string[] = [];
  let depth = 0;
  let current = "";
  for (const character of value) {
    if (character === "(") depth += 1;
    if (character === ")") depth -= 1;
    if (depth === 0 && (character === "," || /\s/.test(character))) {
      if (current) terms.push(current);
      current = "";
      continue;
    }
    current += character;
  }
  if (current) terms.push(current);
  return terms;
}

type SyntaxMatcher = (value: string) => boolean;

function compileSyntax(syntax: string): SyntaxMatcher | null {
  const trimmed = syntax.trim();
  if (trimmed === "*") return () => true;
  if (!trimmed.includes("<")) {
    const keywords = trimmed.split("|").map((keyword) => keyword.trim());
    if (!keywords.every((keyword) => keywordPattern.test(keyword))) return null;
    return (value) => keywords.includes(value);
  }
  const typed = /^<([a-z-]+)>([+#])?$/i.exec(trimmed);
  if (!typed) return null;
  const matchesTerm = baseTypeMatchers[typed[1].toLowerCase()];
  if (!matchesTerm) return null;
  const acceptsTerm = (term: string) => computedValuePattern.test(term) || matchesTerm(term);
  const maximumTerms = typed[2] ? Number.POSITIVE_INFINITY : 1;
  return (value) => {
    const terms = splitTopLevelTerms(value);
    return terms.length > 0 && terms.length <= maximumTerms && terms.every(acceptsTerm);
  };
}

const matchersBySyntax = new Map<string, SyntaxMatcher | null>();

function matchesSyntax(syntax: string, value: string) {
  if (!matchersBySyntax.has(syntax)) matchersBySyntax.set(syntax, compileSyntax(syntax));
  const matcher = matchersBySyntax.get(syntax);
  return matcher ? matcher(value) : false;
}

function balancedCssValue(value: string) {
  const withoutStrings = value.replace(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'/g, "");
  if (/["']/.test(withoutStrings)) return false;
  let depth = 0;
  for (const character of withoutStrings) {
    if (character === "(") depth += 1;
    else if (character === ")") depth -= 1;
    if (depth < 0) return false;
  }
  return depth === 0;
}

const KNOB_PREFIX = "--cui-";

// Not part of validateKnobOverrides, which answers whether a declaration is legal CSS on a real knob: a
// recipe may fix a colour deliberately, and several do. This is a rule about generated values only. A
// generation runs for one appearance, so a literal colour authored in dark mode stays painted after the
// user switches to light, while a token carries both modes for free. A knob declared <color> can be
// checked exactly; one declared * may embed a colour anywhere, so there the test is for the notations a
// model actually writes.
const MODE_SAFE_COLORS = ["transparent", "currentcolor", "inherit"];
const COLOR_LITERAL = /#[0-9a-f]{3,8}\b|\b(?:oklch|oklab|lch|lab|rgba?|hsla?|hwb|color-mix|color)\(/i;

export function colorComesFromTokens(knobName: string, value: string): boolean {
  if (value.includes("var(--")) return true;
  const syntax = knobsByName.get(knobName)?.syntax;
  if (syntax === undefined) return true;
  if (syntax.includes("<color>")) return MODE_SAFE_COLORS.includes(value.trim().toLowerCase());
  return !COLOR_LITERAL.test(value);
}

type KnobDecision = { reason: string } | { selector: string };

function decideKnob(name: string, value: string): KnobDecision {
  if (!value) return { reason: "value must not be empty" };
  if (value.length > MAX_VALUE_LENGTH) return { reason: `value is longer than ${MAX_VALUE_LENGTH} characters` };
  if (!name.startsWith(KNOB_PREFIX)) return { reason: `name must start with ${KNOB_PREFIX}` };
  const knob = knobsByName.get(name);
  if (!knob) return { reason: "name is not a registered knob" };
  if (!knob.selector) return { reason: "knob is registered but never declared on a rule, so it has no selector to write on" };
  if (/[;{}\n\r]/.test(value)) return { reason: "value contains declaration-breaking characters" };
  if (/\/\*|\*\/|@import|url\s*\(|expression\s*\(|javascript:|data:/i.test(value)) {
    return { reason: "value contains unsafe CSS syntax" };
  }
  if (!balancedCssValue(value)) return { reason: "value has unbalanced parentheses or quotes" };
  if (!matchesSyntax(knob.syntax, value)) return { reason: `value does not match the declared syntax ${knob.syntax}` };
  return { selector: knob.selector };
}

export function validateKnobOverrides(input: unknown): { rules: readonly KnobRule[]; rejected: readonly KnobRejection[] } {
  const rules: KnobRule[] = [];
  const rejected: KnobRejection[] = [];
  if (typeof input !== "object" || input === null || Array.isArray(input)) {
    return { rules, rejected: [{ name: "", reason: "knob overrides must be an object of knob name to CSS value" }] };
  }
  for (const [name, raw] of Object.entries(input)) {
    if (typeof raw !== "string") {
      rejected.push({ name, reason: "value must be a string" });
      continue;
    }
    const value = raw.trim();
    const decision = decideKnob(name, value);
    if ("reason" in decision) {
      rejected.push({ name, reason: decision.reason });
      continue;
    }
    const existing = rules.find((rule) => rule.selector === decision.selector);
    if (existing) existing.tokens[name] = value;
    else rules.push({ selector: decision.selector, tokens: { [name]: value } });
  }
  return { rules, rejected };
}
