// Generated from src/registry/sources/control-ui/recipes/flow.css by scripts/gen-knob-contracts.ts — run `bun run sync:knobs`.
export const flowKnobs = [
  "--cui-flow-background",
  "--cui-flow-grid-dot-color",
  "--cui-flow-edge-stroke",
  "--cui-flow-selected-edge-stroke",
  "--cui-flow-edge-size",
  "--cui-flow-node-background",
  "--cui-flow-node-foreground",
  "--cui-flow-node-border-color",
  "--cui-flow-node-hover-border-color",
  "--cui-flow-node-selected-border-color",
  "--cui-flow-node-border-width",
  "--cui-flow-node-radius",
  "--cui-flow-node-shadow",
  "--cui-flow-handle-size",
  "--cui-flow-handle-background",
  "--cui-flow-handle-border-color",
  "--cui-flow-handle-border-width",
  "--cui-flow-edge-label-background",
  "--cui-flow-edge-label-foreground",
  "--cui-flow-edge-label-border-color",
  "--cui-flow-edge-label-border-width",
  "--cui-flow-controls-item-radius",
  "--cui-flow-controls-padding",
  "--cui-flow-controls-radius",
  "--cui-flow-controls-background",
  "--cui-flow-controls-border-color",
  "--cui-flow-controls-shadow",
] as const;
export type FlowKnobStyle = Partial<Record<(typeof flowKnobs)[number], string>>;
