// Generated from src/registry/sources/control-ui/recipes/popup.css by scripts/gen-knob-contracts.ts — run `bun run sync:knobs`.
export const popupKnobs = [
  "--cui-popup-title-foreground",
  "--cui-popup-title-font-size",
  "--cui-popup-title-font-weight",
  "--cui-popup-title-line-height",
  "--cui-popup-title-letter-spacing",
  "--cui-popup-description-foreground",
  "--cui-popup-close-inset",
  "--cui-popup-item-inset",
  "--cui-popup-label-padding-block",
  "--cui-popup-label-padding-inline",
  "--cui-popup-label-font-size",
  "--cui-popup-label-font-weight",
  "--cui-popup-label-letter-spacing",
  "--cui-popup-label-text-transform",
  "--cui-popup-separator-inset",
  "--cui-popup-shortcut-font-size",
  "--cui-popup-shortcut-letter-spacing",
  "--cui-popup-status-success-foreground",
  "--cui-popup-status-warning-foreground",
  "--cui-popup-status-info-foreground",
  "--cui-popup-status-error-foreground",
  "--cui-popup-radius",
  "--cui-popup-background",
  "--cui-popup-foreground",
  "--cui-popup-border-color",
  "--cui-popup-border-width",
  "--cui-popup-shadow",
  "--cui-popup-backdrop-filter",
  "--cui-popup-backdrop-background",
  "--cui-popup-backdrop-blur",
  "--cui-popup-item-radius",
  "--cui-popup-item-font-size",
  "--cui-popup-item-icon-size",
  "--cui-popup-item-padding-block",
  "--cui-popup-item-padding-inline",
  "--cui-popup-item-min-height",
  "--cui-popup-item-highlight-shadow",
  "--cui-popup-item-foreground",
  "--cui-popup-item-highlight-background",
  "--cui-popup-item-highlight-foreground",
  "--cui-popup-item-highlight-muted-foreground",
  "--cui-popup-item-disabled-opacity",
  "--cui-popup-separator-color",
  "--cui-popup-shortcut-foreground",
] as const;
export type PopupKnobStyle = Partial<Record<(typeof popupKnobs)[number], string>>;
