// Generated from src/registry/sources/control-ui/recipes/table-of-contents.css by scripts/gen-knob-contracts.ts — run `bun run sync:knobs`.
export const tableOfContentsKnobs = [
  "--cui-table-of-contents-background",
  "--cui-table-of-contents-border-color",
  "--cui-table-of-contents-border-width",
  "--cui-table-of-contents-radius",
  "--cui-table-of-contents-shadow",
  "--cui-table-of-contents-backdrop-filter",
  "--cui-table-of-contents-padding",
  "--cui-table-of-contents-label-foreground",
  "--cui-table-of-contents-label-font-size",
  "--cui-table-of-contents-label-font-weight",
  "--cui-table-of-contents-label-gap",
  "--cui-table-of-contents-item-foreground",
  "--cui-table-of-contents-item-hover-foreground",
  "--cui-table-of-contents-item-active-foreground",
  "--cui-table-of-contents-item-font-size",
  "--cui-table-of-contents-item-line-height",
  "--cui-table-of-contents-item-font-weight",
  "--cui-table-of-contents-item-root-font-weight",
  "--cui-table-of-contents-item-padding-block",
  "--cui-table-of-contents-item-padding-inline",
  "--cui-table-of-contents-item-indent-size",
  "--cui-table-of-contents-rail-background",
  "--cui-table-of-contents-rail-size",
  "--cui-table-of-contents-trail-background",
  "--cui-table-of-contents-trail-size",
  "--cui-table-of-contents-trail-radius",
  "--cui-table-of-contents-highlight-radius",
  "--cui-table-of-contents-highlight-background",
] as const;
export type TableOfContentsKnobStyle = Partial<Record<(typeof tableOfContentsKnobs)[number], string>>;
